package com.scheduler.backend.entities;
import lombok.*;

import jakarta.persistence.*;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Size;
import java.time.LocalDate;

@Data
@AllArgsConstructor
@NoArgsConstructor
@Builder
@Entity
@Table(name = "checklist_item")
public class ChecklistItem {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @NotNull
    @ManyToOne(fetch = FetchType.LAZY) // assuming FetchType.LAZY for better performance
    @JoinColumn(name = "checklist_id", nullable = false)
    private Checklist checklist;

    @NotNull
    @Size(max = 255)
    @Column(name = "name", length = 255, nullable = false)
    private String name;

    @Column(name = "deadline")
    private LocalDate deadline;

    @Column(name = "flag")
    private Boolean flag;

    // Constructors, getters, setters can be generated by Lombok @Data annotation

}