package com.scheduler.backend.dtos;

import com.scheduler.backend.entities.Checklist;
import lombok.*;

import jakarta.validation.constraints.*;

import java.time.LocalDate;

@Data
@AllArgsConstructor
@NoArgsConstructor
@Builder
public class ChecklistItemDto {

    private Long id;

    @NotNull
    private Checklist checklistId;

    @NotBlank
    @Size(max = 255)
    private String name;

    private LocalDate deadline;

    private Boolean flag;

    // Constructors, getters, setters can be generated by Lombok @Data annotation
}