package com.scheduler.backend.dtos;

import com.scheduler.backend.entities.TypeOfTask;
import lombok.*;

import jakarta.validation.constraints.*;
import java.time.LocalDate;
import java.time.LocalDateTime;

@Data
@AllArgsConstructor
@NoArgsConstructor
@Builder
public class TaskDto {

    private Long id;

    @NotBlank
    @Size(max = 255)
    private String name;

    private TypeOfTask typeId;

    private String description;

    private LocalDate deadline;

    private LocalDateTime createdAt;

    // Constructors, getters, setters can be generated by Lombok @Data annotation
}